# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=35)),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Image', models.ImageField(blank=True, upload_to='post_image')),
                ('Created_At', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
